### ISSUE TITLE
v0.3.00

### ISSUE THREAD

**Issue by rossdotparker** [GibbonEdu/module-tripPlanner#22]
Hi Ray. We've got some v18 compatibility issues, and some feature requests, and so I am going to work on v0.3.00. Let me know if this causes any issues.

I think I'll remove the calculation of missed classes. I know this was where the unit began, but we are not using it, and it slows the load time down a lot. Sound OK?

I'll hopefully push things through later on today.

My guess (hope?) is you are too busy to maintain this for now, and won't mind me steering the ship for a while.

**Comment by jimbo8098** [comment]
Looks like this is resolved now https://github.com/GibbonEdu/module-tripPlanner/pull/24
